@startuml
left to right direction
skinparam backgroundColor #B6E3A6

actor "Docente" as docente

package "Sistema SYS COLEGIO EMANUEL" {
    usecase "Registrar Notas" as registrar
    usecase "Autenticar Usuario" as auth
    usecase "Seleccionar Curso y Alumno" as seleccionar
    usecase "Validar Rango de Nota" as validar
    usecase "Calcular Promedio" as promedio
    usecase "Notificar al Padre" as notificar
}

docente --> registrar

registrar ..> auth : <<include>>
registrar ..> seleccionar : <<include>>
registrar ..> validar : <<include>>
registrar ..> promedio : <<include>>
registrar ..> notificar : <<include>>

@enduml