@startuml
left to right direction
skinparam backgroundColor #B6E3A6

actor "Docente" as docente

package "Sistema SYS COLEGIO EMANUEL" {
    usecase "Publicar Avance y Tareas" as publicar
    usecase "Autenticar Usuario" as auth
    usecase "Seleccionar Curso" as seleccionar
    usecase "Subir Fotos de Clase" as fotos
    usecase "Asignar Tarea" as tarea
    usecase "Notificar a Padres" as notificar
}

docente --> publicar

publicar ..> auth : <<include>>
publicar ..> seleccionar : <<include>>
publicar ..> fotos : <<extend>>
publicar ..> tarea : <<extend>>
publicar ..> notificar : <<include>>

@enduml