@startuml
skinparam backgroundColor #FFF0F5
skinparam stateBackgroundColor #FFD1DC
skinparam stateBorderColor #C71585
skinparam arrowColor #C71585

[*] --> Generada
Generada --> Pendiente : Inicio de mes
Pendiente --> ProcesandoPago : Padre realiza pago
ProcesandoPago --> Pagada : Pago exitoso
ProcesandoPago --> Rechazada : Fallo de pasarela/tarjeta
Rechazada --> Pendiente : Padre reintentar
Pendiente --> Vencida : Pasa la fecha limite
Vencida --> ProcesandoPago : Padre paga con mora
Pagada --> [*] : Fin del ciclo
Vencida --> Anulada : Condonacion admin
Anulada --> [*]

@enduml